site_name: "PathoGenX ü¶†üß¨üó∫Ô∏è"
site_url: https://tomdstanton.github.io/pathogenx
repo_url: https://github.com/tomdstanton/pathogenx
site_description: "A Python library for Pathogen Genotype eXploration"
repo_name: "tomdstanton/pathogenx"
watch: [mkdocs.yml, README.md, src]

nav:
  - Home: index.md

theme:
  name: "material"
  icon:
    logo: 'material/microbiology'
  homepage: https://tomdstanton.github.io/pathogenx
  palette:
    - scheme: default
      primary: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - toc.follow
    - content.action.edit

markdown_extensions:
  - admonition
#  - attr_list
#  - pymdownx.emoji:
#      emoji_index: !!python/name:material.extensions.emoji.twemoji
#      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: "google"
  - api-autonav:
      modules: ['src/pathogenx']
      nav_section_title: "API Reference"