[project]
authors = [{name = "Tom Stanton", email = "tomdstanton@gmail.com"}]
name = "pathogenx"
dynamic = ["urls", "version"]
description = "Pathogen Genotype eXplorer"
requires-python = ">=3.11"
dependencies = ["pandas", "scipy"]

[project.optional-dependencies]
test = ["pytest"]
models = ["numpyro"]
docs = ["mkdocs-material", "mkdocs-api-autonav>=0.3.0,<0.4"]
dev = ["pathogenx[test,docs,models]"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "hatch-vcs"]

[tool.hatch.version]
source = "vcs"
